//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

protocol ___VARIABLE_sceneName___PresentationLogic{
    func presentSomething(response: ___VARIABLE_sceneName___.Something.Response)
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresentationLogic{
    weak var viewController: ___VARIABLE_sceneName___DisplayLogic?
    
    // ------------------------------------------------------------
    // INIT-DEINIT
    // ------------------------------------------------------------
    // MARK: - Init-Deinit
    init(viewController: ___VARIABLE_sceneName___DisplayLogic?) {
        self.viewController = viewController
    }

    // ------------------------------------------------------------
    // PRESENTATION LOGIC
    // ------------------------------------------------------------
    // MARK: - Presentation Logic
    func presentSomething(response: ___VARIABLE_sceneName___.Something.Response){
        let viewModel = ___VARIABLE_sceneName___.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
