//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_sceneName___WorkerTests: XCTestCase{
	
    // MARK: Subject under test
    var sut: ___VARIABLE_sceneName___Worker!

    override func setUp(){
        super.setUp()
        setup___VARIABLE_sceneName___Worker()
    }
  
    override func tearDown(){
        super.tearDown()
    }
  
	// ------------------------------------------------------------
	// SETUP
	// ------------------------------------------------------------
	// MARK: - Setup
    func setup___VARIABLE_sceneName___Worker(){
        sut = ___VARIABLE_sceneName___Worker()
    }
	
	// ------------------------------------------------------------
	// TESTS
	// ------------------------------------------------------------
	// MARK: - Tests
    func testSomething(){
        // Given

        // When

        // Then
    }
}
