//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_sceneName___InteractorTests: XCTestCase{
	
    // MARK: Subject under test
    var sut: ___VARIABLE_sceneName___Interactor!

    override func setUp(){
        super.setUp()
        setup___VARIABLE_sceneName___Interactor()
    }
  
    override func tearDown(){
        super.tearDown()
    }
  
	// ------------------------------------------------------------
	// TEST SETUP
	// ------------------------------------------------------------
	// MARK: - Test Setup
    func setup___VARIABLE_sceneName___Interactor(){
        sut = ___VARIABLE_sceneName___Interactor(presenter: nil)
    }
  
	// ------------------------------------------------------------
	// TESTS
	// ------------------------------------------------------------
	// MARK: - Tests
    func testDoSomething(){
        // Given
        let spy = ___VARIABLE_sceneName___PresentationLogicSpy()
        sut.presenter = spy
        let request = ___VARIABLE_sceneName___.Something.Request()

        // When
        sut.doSomething(request: request)

        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
