//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

// ------------------------------------------------------------
// TEST SPIES
// ------------------------------------------------------------
// MARK: - Test Spies
// Presenter
class ___VARIABLE_sceneName___PresentationLogicSpy: ___VARIABLE_sceneName___PresentationLogic{
}

// ViewController
class ___VARIABLE_sceneName___DisplayLogicSpy: ___VARIABLE_sceneName___DisplayLogic{

}

// Interactor
class ___VARIABLE_sceneName___BusinessLogicSpy: ___VARIABLE_sceneName___BusinessLogic{

}

// Router
class ___VARIABLE_sceneName___RouterSpy: NSObject, ___VARIABLE_sceneName___RoutingLogic,___VARIABLE_sceneName___DataPassing{
	var dataStore: ___VARIABLE_sceneName___DataStore?
}
