//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import Foundation

protocol ___VARIABLE_sceneName___BusinessLogic{
    func doSomething(request: ___VARIABLE_sceneName___.Something.Request)
}

protocol ___VARIABLE_sceneName___DataStore{
    //var name: String { get set }
}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___BusinessLogic, ___VARIABLE_sceneName___DataStore{
    var presenter: ___VARIABLE_sceneName___PresentationLogic?
    var worker: ___VARIABLE_sceneName___Worker?
    //var name: String = ""
    
    // ------------------------------------------------------------
    // INIT-DEINIT
    // ------------------------------------------------------------
    // MARK: - Init-Deinit
    init( presenter: ___VARIABLE_sceneName___PresentationLogic?, worker: ___VARIABLE_sceneName___Worker? = ___VARIABLE_sceneName___Worker() ){
        self.presenter = presenter
        self.worker = worker
    }

    // ------------------------------------------------------------
    // BUSINESS LOGIC
    // ------------------------------------------------------------
    // MARK: - Business Logic
    func doSomething(request: ___VARIABLE_sceneName___.Something.Request){
        self.worker?.doSomeWork()

        let response = ___VARIABLE_sceneName___.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
