//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

enum ___VARIABLE_sceneName___ {
	
	// ------------------------------------------------------------
	// DISPLAYABLES
	// ------------------------------------------------------------
	// MARK: - Displayables
	struct DisplayableSomething{
		var name : String?
	}

	// ------------------------------------------------------------
	// USE CASES
	// ------------------------------------------------------------
	// MARK: - Use cases
    enum Something {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
